/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SlpToolKit_NativeCyk_InfosPhrase */

#ifndef _Included_SlpToolKit_NativeCyk_InfosPhrase
#define _Included_SlpToolKit_NativeCyk_InfosPhrase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SlpToolKit_NativeCyk_InfosPhrase
 * Method:    constructor
 * Signature: (JJLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_SlpToolKit_NativeCyk_00024InfosPhrase_constructor
  (JNIEnv *, jclass, jlong, jlong, jstring, jlong);

/*
 * Class:     SlpToolKit_NativeCyk_InfosPhrase
 * Method:    destructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SlpToolKit_NativeCyk_00024InfosPhrase_destructor
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
