/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SlpToolKit_Lexematizor */

#ifndef _Included_SlpToolKit_Lexematizor
#define _Included_SlpToolKit_Lexematizor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SlpToolKit_Lexematizor
 * Method:    internalLexematize
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_SlpToolKit_Lexematizor_internalLexematize
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
