/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SlpToolKit_NativeRetourRechercheValeurLexico */

#ifndef _Included_SlpToolKit_NativeRetourRechercheValeurLexico
#define _Included_SlpToolKit_NativeRetourRechercheValeurLexico
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SlpToolKit_NativeRetourRechercheValeurLexico
 * Method:    destructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SlpToolKit_NativeRetourRechercheValeurLexico_destructor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SlpToolKit_NativeRetourRechercheValeurLexico
 * Method:    found
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_SlpToolKit_NativeRetourRechercheValeurLexico_found
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SlpToolKit_NativeRetourRechercheValeurLexico
 * Method:    getLastMatchChar
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SlpToolKit_NativeRetourRechercheValeurLexico_getLastMatchChar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SlpToolKit_NativeRetourRechercheValeurLexico
 * Method:    getKey
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_SlpToolKit_NativeRetourRechercheValeurLexico_getKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SlpToolKit_NativeRetourRechercheValeurLexico
 * Method:    next
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_SlpToolKit_NativeRetourRechercheValeurLexico_next
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
