/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SlpToolKit_NativeCyk_RetourLexicalise */

#ifndef _Included_SlpToolKit_NativeCyk_RetourLexicalise
#define _Included_SlpToolKit_NativeCyk_RetourLexicalise
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SlpToolKit_NativeCyk_RetourLexicalise
 * Method:    destructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SlpToolKit_NativeCyk_00024RetourLexicalise_destructor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SlpToolKit_NativeCyk_RetourLexicalise
 * Method:    getTableCYK
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_SlpToolKit_NativeCyk_00024RetourLexicalise_getTableCYK
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SlpToolKit_NativeCyk_RetourLexicalise
 * Method:    getDecoupage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_SlpToolKit_NativeCyk_00024RetourLexicalise_getDecoupage
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
